#!/bin/bash

# Bash settings (do not mess with it)
shopt -s nullglob globstar
# =) unless you have read the following with good care! =)
# https://www.gnu.org/software/bash/manual/html_node/The-Shopt-Builtin.html

# Get the script name and its file real path
SCRIPT_PATH="$(dirname "$(readlink -f "$0")")"
SCRIPT_NAME="${0##*/}"

# Init arguments
LOCAL_REPO_URL=https://github.com/evertramos/learning-python-001
LOCAL_CONTAINER_NAME="ezy-python"

# Usage function
usage_local() {
    echo "Usage: $SCRIPT_NAME [options]"
    echo "Options:"
    echo "  -i, install   Install dependencies"
    echo "  -r, run       Run the application"
    echo "  -d, dev       Run the application in development mode"
    echo "  -b, build     Build the application container image"
    echo "  -h, help      Show this help message"
}

# Show usage if no arguments are provided
if [[ $# -eq 0 ]]; then
    usage_local
    exit 0
fi

# Process arguments
while [[ $# -gt 0 ]]
do
    case "$1" in
        -i | install)
        LOCAL_INSTALL=true
        shift 1
        ;;
        -r | run)
        LOCAL_RUN=true
        shift 1
        ;;
        -d | dev)
        LOCAL_DEV=true
        shift 1
        ;;
        -b | build)
        LOCAL_BUILD=true
        shift 1
        ;;
        -h | help)
        usage_local
        exit 0
        ;;
        *)
        echoerror "Unknown argument: $1" false
        usage_local
        exit 0
        ;;
    esac
done

# Install the script
if [[ "${LOCAL_INSTALL,,}" == "true" ]]; then
    echo "Clone the repository..."
    git clone "${LOCAL_REPO_URL}" || {
        echo "Failed to clone the repository."
        exit 1
    }
    echo "Repository cloned successfully."
    echo ""
    echo "Please run the following:"
    echo "cd $(basename "${LOCAL_REPO_URL}" .git)"
    echo "./${SCRIPT_NAME} run"
    echo ""
    exit 0
fi

# Run the application
if [[ "${LOCAL_RUN,,}" == "true" ]]; then
    echo "Running the application..."

    # Check if Docker is installed
    if [[ -z "$(command -v docker)" ]]; then
        LOCAL_DOCKER=false
    else
        LOCAL_DOCKER=true
    fi

    # Check if Python is installed if Docker is not available
    if [[ "${LOCAL_DOCKER,,}" == "false" || -z "$(command -v python3)" ]]; then
        echo "Docker or Python must be installed."
        exit 1
    else
        LOCAL_PYTHON=true
    fi

    # Run the applicaetion
    if [[ "${LOCAL_DOCKER,,}" == "true" ]]; then
        echo "Building and running the Docker container."
        docker build -t "${LOCAL_CONTAINER_NAME}" .
        docker run --rm -it --name ezy-iesb "${LOCAL_CONTAINER_NAME}" python main.py || {
            echo "Failed to run the Docker container."
            exit 1
        }
    else
        echo "Running the application without Docker..."
        python3 src/main.py
    fi
fi

# Run dev
if [[ "${LOCAL_DEV,,}" == "true" ]]; then
    echo "Running the application in development mode..."
    docker run --rm -it -v "$(pwd)/src":/usr/src/app "${LOCAL_CONTAINER_NAME}" python3 /usr/src/app/main.py
fi

# Build docker image
if [[ "${LOCAL_BUILD,,}" == "true" ]]; then
    echo "Building the application image."
    docker build -t "${LOCAL_CONTAINER_NAME}" .
fi

exit 0
